name: Build and Publish docker image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'dev'


jobs:
    compile:
        name: Validate data set
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v4
          - name: Run the validation
            uses: addnab/docker-run-action@v3
            with:
                image: ghcr.io/demeringo/csv-validator-docker-image:0.0.1-alpha
                options: -v ${{ github.workspace }}/data:/data
                run: |
                    frictionless validate /data/countries.ressource.yaml
